### ISSUE TITLE
Self hosted server

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/itc-api#3]
Add a “deploy to heroku” button for self hosting the server api.

Follow up of tweet by @krausefx
https://twitter.com/krausefx/status/947841238153252865

**Comment by eliottha** [comment]
Done @RishabhTayal

**Comment by KrauseFx** [comment]
Awesome. I'd remove the button from the README for now, until the project is completely ready to be used, and is battle tested, so that people finding this repo don't deploy this service

**Comment by eliottha** [comment]
ok. Understand @KrauseFx !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@krausefx Removed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
